SMALLG = [
    "Write a heartfelt note",
    "Cook a special dinner",
    "Plan a movie night",
    "Send a sweet text during the day",
    "Surprise with favorite snacks",
    "Buy a card for no reason",
    "Make a playlist of favorite songs",
    "Plan a date night",
    "Send a care package",
    "Make a handmade gift",
    "Leave a love note on the bathroom mirror",
    "Cook breakfast in bed",
    "Plan a surprise lunch date",
    "Send a cute animal GIF to brighten their day",
    "Organize a cozy at-home spa night",
    "Create a photo album with special memories",
    "Surprise with a favorite book or magazine",
    "Plan a scenic walk or hike together",
    "Leave a love letter in their bag or purse",
    "Send a postcard from a place you've been",
    "Plan a surprise visit to their workplace",
    "Create a customized crossword or puzzle",
    "Surprise with a favorite dessert",
    "Plan a game night with their favorite games",
    "Leave surprise sticky notes with affirmations",
    "Send a voice message with sweet words",
    "Organize a virtual movie night together",
    "Create a list of reasons why you love them",
    "Plan a sunset or sunrise viewing together",
    "Surprise with a small plant or flower",
    "Write and hide love messages around the house",
    "Plan a picnic in the backyard",
    "Send a virtual hug emoji",
    "Make a compilation of favorite jokes",
    "Organize a surprise virtual date",
    "Plan a day of doing their favorite activities",
    "Send a link to a song that reminds you of them",
    "Surprise with a personalized keychain",
    "Create a DIY coupon book for special favors",
    "Plan a stargazing night",
    "Leave a surprise love letter in their car",
    "Send a digital drawing or doodle",
    "Organize a surprise dinner with friends",
    "Plan a scenic drive with their favorite music",
    "Surprise with a cozy blanket or scarf",
    "Create a list of shared dreams and goals",
    "Send a funny meme to brighten their day",
    "Plan a surprise online cooking class",
    "Leave a small surprise in their jacket pocket",
    "Go to an improv class together",
    "Send a virtual kiss emoji"
]

MEDIUMG = [
    "Take a day off together",
    "Go to an improv class together",
    "Plan a weekend getaway",
    "Organize a picnic in the park",
    "Massage day",
    "Create a scrapbook of memories",
    "Buy some flowers",
    "Plan a surprise visit to a museum",
    "Plan a surprise visit to a botanical garden",
    "Drop off a surprise at work",
    "Plan a scenic bike ride together",
    "Have a candlelit dinner at home",
    "Take a cooking class as a couple",
    "Plan a surprise beach day",
    "Go on a hot air balloon ride",
    "Visit a local art gallery together",
    "Explore a nearby hiking trail",
    "Organize a game night with friends",
    "Have a cozy night by the fireplace",
    "Plan a pottery or art class",
    "Attend a live performance or show",
    "Take a scenic drive to enjoy the view",
    "Visit a historical landmark together",
    "Organize a virtual double date",
    "Plan a surprise concert night",
    "Go wine tasting at a local vineyard",
    "Visit a rooftop bar for sunset drinks",
    "Have a DIY pizza-making night",
    "Plan a weekend camping trip",
    "Take a dance lesson together",
    "Visit a local farmers' market",
    "Plan a surprise visit to a zoo",
    "Explore a nearby city for the day",
    "Have a movie marathon at home",
    "Attend a local festival or fair",
    "Plan a surprise visit to an aquarium",
    "Go on a scenic boat ride",
    "Visit a botanical garden together",
    "Organize a karaoke night at home",
    "Plan a surprise visit to a comedy show",
    "Take a painting or art workshop",
    "Visit a local sports event together",
    "Have a themed costume night at home",
    "Plan a surprise visit to a planetarium",
    "Explore a nearby nature reserve",
    "Go on a spontaneous road trip",
    "Visit a local escape room",
    "Plan a surprise visit to a historical site",
    "Have a picnic at a nearby lake or river",
    "Explore a local art or craft fair",
    "Organize a virtual game night with friends"
]

LARGEG = [
    "Plan a surprise vacation",
    "Plan a surprise party",
    "Plan a surprise visit to an amusement park",
    "Go to an improv class together",
    "Organize a private dinner",
    "Gift a piece of meaningful jewelry",
    "Create a personalized star map",
    "Plan a surprise visit to a concert",
    "Plan a surprise visit to a play",
    "Organize a weekend cruise getaway",
    "Plan a surprise visit to a West End show",
    "Arrange a private chef for a special dinner",
    "Gift a weekend stay at a luxury resort",
    "Plan a surprise helicopter tour",
    "Organize a private yacht excursion",
    "Create a customized fireworks display",
    "Plan a surprise visit to a tropical island",
    "Arrange a private concert for your partner",
    "Gift a weekend at a cozy mountain cabin",
    "Plan a surprise visit to a world-renowned spa",
    "Organize a hot air balloon festival experience",
    "Gift a personalized piece of art",
    "Arrange a private movie screening",
    "Gift a weekend at a historic castle",
    "Plan a surprise visit to a wildlife safari",
    "Gift a piece of custom-designed clothing",
    "Plan a surprise visit to a famous landmark",
    "Arrange a helicopter flight for sightseeing",
    "Plan a surprise visit to a world-class museum",
    "Organize a private stargazing experience",
    "Gift a piece of custom-made furniture",
    "Gift a weekend at a picturesque lakeside retreat",
    "Plan a surprise visit to a Michelin-starred restaurant",
    "Organize a private concert under the stars",
    "Plan a surprise visit to a famous sports event",
    "Organize a private opera performance",
    "Gift a piece of custom-engraved glassware",
    "Plan a surprise visit to a high-profile event",
    "Arrange a private tour of a historic mansion",
    "Gift a weekend at a five-star mountain retreat"
]
